### ISSUE TITLE
Editor bug: picking a model from configuration dropdown menu fails node

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#304]
NullPointer Exception
![image.png](https://images.zenhubusercontent.com/5e4ba30f8f780f7f48f8f306/d5245c84-79c3-4b05-b32d-8ba476a105e0)

**Comment by miguelalba** [comment]
The editor node throws a NPE after picking a class and executing it. It occurs before opening the JS view.

```
java.lang.NullPointerException
	at metadata.SwaggerUtil.getParameter(SwaggerUtil.java:574)
	at de.bund.bfr.knime.fsklab.v2_0.editor.FSKEditorJSNodeModel.performExecute(FSKEditorJSNodeModel.java:325)
	at org.knime.js.core.node.AbstractWizardNodeModel.execute(AbstractWizardNodeModel.java:136)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:576)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1236)
	at org.knime.core.node.Node.execute(Node.java:1016)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:558)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:334)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
```

**Comment by miguelalba** [comment]
Ok. I did not write this code and I am hesitant to change it.

```java
      boolean regenerateSimulation = false;
      // Take parameters from view value (metadata)
      List<Parameter> parameters = new ArrayList<>();
      if(metadata != null)
        parameters = SwaggerUtil.getParameter(metadata);
      // Take original parameters from view representation (metadata)
      List<Parameter> originalParameters = new ArrayList<>();
      if(originalMetadata != null)
        originalParameters = SwaggerUtil.getParameter(originalMetadata);
      
      if(originalParameters.size()>0 && !parameters.equals(originalParameters) || m_port == null){
        regenerateSimulation = true;
      }
```

The problem with this snippet is that it does not check if model math or parameters are null like I do in the following snippet (just a few lines below).

```java
      // Take simulation from view value otherwise from input port (if connected)
      if (metadata != null && SwaggerUtil.getModelMath(metadata) != null
          && SwaggerUtil.getParameter(metadata) != null && regenerateSimulation)  {

        // 1. Create new default simulation out of the view value
        FskSimulation newDefaultSimulation = NodeUtils.createDefaultSimulation(parameters);

        // 2. Assign newDefaultSimulation
        simulations = Arrays.asList(newDefaultSimulation);
      }
```

Since I did not write the first snippet, I do not know if not setting *regenerateSimulation* or the *originalParameters* would break functionality in the joiner or simulator nodes. I will try to fix it, just checking null, but I will need both @ahmadswaid and @schuelet to review it.

**Comment by miguelalba** [comment]
More or less a list of things to change:
1. NPE in regenerateSimulation snippet. Solved locally.
2. NPE in generation of model identifiers when some models do not have general information yet. Solved locally.
3. NPE when changing to another model class and trying to load old metadata. There is a conflict between view representation and view value. I think the metadata being pulled from the representation is an error. It was always used only in the view.
4. When most NPEs are fixed the JS view does not load for data models.
<img width="831" alt="Screenshot 2021-04-16 at 19 21 19" src="https://user-images.githubusercontent.com/19906968/115061083-f8e09080-9ee8-11eb-9ec6-f35360a330e4.png">

**Comment by schuelet** [comment]
fixed as of https://github.com/SiLeBAT/FSK-Lab/pull/856
